[model]
name = "three_species_system"
states = [
    { name = "x1", initial_value = 1.5, estimate = true },
    { name = "x2", initial_value = 0.2, estimate = true },
    { name = "x3", initial_value = 0.3, estimate = true }
]

parameters = [
    { name = "a", value = 0.7, bounds = [-1e2, 1e2], scale = "lin" },
    { name = "b", value = -0.8, bounds = [-1e2, 1e2], scale = "lin" },
    { name = "c", value = -0.3, bounds = [-1e2, 1e2], scale = "lin" },
    { name = "d", value = -0.4, bounds = [-1e2, 1e2], scale = "lin" }
]

equations = [
    "x1' = -a * x1",
    "x2' = -(b * b) * x2",
    "x3' = -(c*c + d*d) * x3"
]


observables = [
    { name = "obs_x1", formula = "pow(x1, 0.5)", transformation = "lin", noise_distribution = "normal" },
    { name = "obs_x2", formula = "x1+x2", transformation = "lin", noise_distribution = "normal" },
    { name = "obs_x3", formula = "x3-x1*x1", transformation = "lin", noise_distribution = "normal" }
]


[simulation]
timespan = [0, 3.0]
n_timepoints = 30
noise_level = 0.0001
output_dir = "blind_petab_problem"
blind = true
