[model]
name = "DAISY_mamil3"
states = [
    { name = "x1", initial_value = 0.25, estimate = true },
    { name = "x2", initial_value = 0.5, estimate = true },
    { name = "x3", initial_value = 0.75, estimate = true },
]
parameters = [
    { name = "a12", value = 0.167, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "a13", value = 0.333, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "a21", value = 0.5, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "a31", value = 0.667, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "a01", value = 0.833, bounds = [-1.0e6, 1.0e6], scale = "lin" },
]
equations = [
    "x1' = (-a01 - a21 - a31)*x1 + a12*x2 + a13*x3",
    "x2' = -a12*x2 + a21*x1",
    "x3' = -a13*x3 + a31*x1",
]
observables = [
    { name = "obs_y1", formula = "x1", transformation = "lin", noise_distribution = "normal" },
    { name = "obs_y2", formula = "x2", transformation = "lin", noise_distribution = "normal" },
]
[simulation]
timespan = [0.0, 1.0]
n_timepoints = 21
noise_level = 1.0e-9
output_dir = "petab_DAISY_mamil3"
blind = true
