[model]
name = "DAISY_mamil4"
states = [
    { name = "x1", initial_value = 0.2, estimate = true },
    { name = "x2", initial_value = 0.4, estimate = true },
    { name = "x3", initial_value = 0.6, estimate = true },
    { name = "x4", initial_value = 0.8, estimate = true },
]
parameters = [
    { name = "k01", value = 0.125, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "k12", value = 0.25, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "k13", value = 0.375, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "k14", value = 0.5, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "k21", value = 0.625, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "k31", value = 0.75, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "k41", value = 0.875, bounds = [-1.0e6, 1.0e6], scale = "lin" },
]
equations = [
    "x1' = -k01*x1 + k12*x2 + k13*x3 + k14*x4 - k21*x1 - k31*x1 - k41*x1",
    "x2' = -k12*x2 + k21*x1",
    "x3' = -k13*x3 + k31*x1",
    "x4' = -k14*x4 + k41*x1",
]
observables = [
    { name = "obs_y1", formula = "x1", transformation = "lin", noise_distribution = "normal" },
    { name = "obs_y2", formula = "x2", transformation = "lin", noise_distribution = "normal" },
    { name = "obs_y3", formula = "x3 + x4", transformation = "lin", noise_distribution = "normal" },
]
[simulation]
timespan = [0.0, 5.0]
n_timepoints = 1001
noise_level = 0.001
output_dir = "petab_DAISY_mamil4"
blind = true
