[model]
name = "simple_linear_combination"
states = [
    { name = "x1", initial_value = 1.0, estimate = true },
    { name = "x2", initial_value = 2.0, estimate = true },
]
parameters = [
    { name = "a", value = 0.4, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "b", value = 0.8, bounds = [-1.0e6, 1.0e6], scale = "lin" },
]
equations = [
    "x1' = -a*x2",
    "x2' = b*x1",
]
observables = [
    { name = "obs_y1", formula = "2.0*x1 + 0.5*x2", transformation = "lin", noise_distribution = "normal" },
    { name = "obs_y2", formula = "3.0*x1 - 0.25*x2", transformation = "lin", noise_distribution = "normal" },
]
[simulation]
timespan = [0.0, 1.0]
n_timepoints = 21
noise_level = 1.0e-9
output_dir = "petab_simple_linear_combination"
blind = true
