[model]
name = "fitzhugh-nagumo"
states = [
    { name = "V", initial_value = 0.333, estimate = true },
    { name = "R", initial_value = 0.67, estimate = true },
]
parameters = [
    { name = "g", value = 0.25, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "a", value = 0.5, bounds = [-1.0e6, 1.0e6], scale = "lin" },
    { name = "b", value = 0.75, bounds = [-1.0e6, 1.0e6], scale = "lin" },
]
equations = [
]
observables = [
    { name = "obs_y1", formula = "V", transformation = "lin", noise_distribution = "normal" },
]
[simulation]
timespan = [0.0, 1.0]
n_timepoints = 21
noise_level = 0.0001
output_dir = "petab_fitzhugh-nagumo"
blind = true
